package com.myteam.rulesbase;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dedupCaseParams implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "policyNumber")
	private java.lang.String policyNumber;

	@org.kie.api.definition.type.Label(value = "vehicleIncidentType")
	private java.lang.String vehicleIncidentType;

	@org.kie.api.definition.type.Label(value = "incidentType")
	private java.lang.String incidentType;

	@org.kie.api.definition.type.Label(value = "vehicleIncidentSubtype")
	private java.lang.String vehicleIncidentSubtype;

	@org.kie.api.definition.type.Label(value = "vehicleRegistrationNumber")
	private java.lang.String vehicleRegistrationNumber;

	@org.kie.api.definition.type.Label(value = "vehicleSequenceNumber")
	private java.lang.String vehicleSequenceNumber;

	public dedupCaseParams() {
	}

	public java.lang.String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(java.lang.String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public java.lang.String getVehicleIncidentType() {
		return this.vehicleIncidentType;
	}

	public void setVehicleIncidentType(java.lang.String vehicleIncidentType) {
		this.vehicleIncidentType = vehicleIncidentType;
	}

	public java.lang.String getIncidentType() {
		return this.incidentType;
	}

	public void setIncidentType(java.lang.String incidentType) {
		this.incidentType = incidentType;
	}

	public java.lang.String getVehicleIncidentSubtype() {
		return this.vehicleIncidentSubtype;
	}

	public void setVehicleIncidentSubtype(
			java.lang.String vehicleIncidentSubtype) {
		this.vehicleIncidentSubtype = vehicleIncidentSubtype;
	}

	public java.lang.String getVehicleRegistrationNumber() {
		return this.vehicleRegistrationNumber;
	}

	public void setVehicleRegistrationNumber(
			java.lang.String vehicleRegistrationNumber) {
		this.vehicleRegistrationNumber = vehicleRegistrationNumber;
	}

	public java.lang.String getVehicleSequenceNumber() {
		return this.vehicleSequenceNumber;
	}

	public void setVehicleSequenceNumber(java.lang.String vehicleSequenceNumber) {
		this.vehicleSequenceNumber = vehicleSequenceNumber;
	}

	public dedupCaseParams(java.lang.String policyNumber,
			java.lang.String vehicleIncidentType,
			java.lang.String incidentType,
			java.lang.String vehicleIncidentSubtype,
			java.lang.String vehicleRegistrationNumber,
			java.lang.String vehicleSequenceNumber) {
		this.policyNumber = policyNumber;
		this.vehicleIncidentType = vehicleIncidentType;
		this.incidentType = incidentType;
		this.vehicleIncidentSubtype = vehicleIncidentSubtype;
		this.vehicleRegistrationNumber = vehicleRegistrationNumber;
		this.vehicleSequenceNumber = vehicleSequenceNumber;
	}

}